apiVersion: v1
kind: Service
metadata:
  name: dataprepsvc
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    app: dataprepapp
    version: v1
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dataprepdeploy
spec:
  selector:
    matchLabels:
      app: dataprepapp
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: dataprepapp
        version: v1
    spec:
      containers:
      - image: laceacr02.azurecr.io/ntfish-dataprep:v1 # UPDATE ACR SERVER
        name: azure
        ports:
        - containerPort: 8888
        volumeMounts:
          - name: azure
            mountPath: /mnt/z
        env: # SET ENV VARIABLES
        - name: MYVAR
          value: MYVARVALUE
      volumes:
      - name: azure
        azureFile:
          secretName: storage-secret
          shareName: raw
          readOnly: false